### PR TITLE
refactor: Refactor the getMatchedRule method and drop support webpack1

### PR DESCRIPTION
**Pull request by rguanghui**
**What kind of change does this PR introduce? (bugfix, feature, docs update, improvement)**
improvement

**What is the current behavior? (You can also link to an open issue here)**
- The way to get loader options is incorrect.
- The wrong path was generated when use `publibPath` option.
- https://github.com/kisenka/svg-sprite-loader/issues/286.

**What is the new behavior (if this is a feature change)?**
- Refactor the getMatchedRule method
- Drop support webpack1

**Does this PR introduce a breaking change?**
Yes, Drop support webpack1.

**Please check if the PR fulfills [contributing guidelines](https://github.com/kisenka/svg-sprite-loader/blob/master/CONTRIBUTING.md#develop)**

### CODE REVIEW

**Comment by vicvinc** [comment]
any feedback about this?

**Comment by kisenka** [comment]
@vicvinc thanks for pinging. Published as `svg-sprite-loader@4.0.0`, due to dropped webpack 1 support.
@rguanghui thanks a lot for your work :)

**Comment by vicvinc** [comment]
@kisenka 
Honored with this.
I'm preparing the mini demo about the  [#286](https://github.com/kisenka/svg-sprite-loader/issues/286) ... does it still necessary?

**Comment by kisenka** [comment]
@vicvinc firstly check the new version with your code and if problem exists give me the demo :)

**Comment by vicvinc** [comment]
@kisenka 

Hi, I'm back.

good news is there are no more errors during compile.

the bad news is SVG sprites was compiled as something like this

image

and I prepared this [repo](https://github.com/vicvinc/webpack-svg-sprites-demo) to reappear.

hope this helps.

thanks again.

**Comment by kisenka** [comment]
@vicvinc two things:
1. Add `esModule: false` option to loader config.
2. It was incorrect publicPath interpolation, I've fixed it in version 4.1.1, please check.

**Comment by vicvinc** [comment]
@kisenka 

works perfectly! 

great work, and here is my star to the repo 🌟( also on the repo

**Pull request merged**
