### PR TITLE
refactor(examples): add examples for webpack dll plugin

### PR DESCRIPTION
**Pull request by steplov**
This is the pull request with example how to use svg sprite loader with webpack DllPlugin.

### CODE REVIEW

**Comment by kisenka** [comment]
@steplov ping :)

**Comment by steplov** [comment]
@kisenka yes? Any questions ?

**Comment by kisenka** [comment]
@steplov oh, sorry, I think that you will be notified when I add comment to review. But I forgot to submit it :)

**Comment by steplov** [comment]
@kisenka done. I didn't get that you use yarn. Now it fixed

**Pull request merged**
