### PR TITLE
Webpack 4 upgrade

### PR DESCRIPTION
**Pull request by rynclark**
**What kind of change does this PR introduce? (bugfix, feature, docs update, improvement)**

Adds webpack 4 support

**What is the current behavior? (You can also link to an open issue here)**

Doesn't support webpack 4

**What is the new behavior (if this is a feature change)?**

Supports webpack 4

**Does this PR introduce a breaking change?**

No

### CODE REVIEW

**Comment by rynclark** [comment]
@kisenka can you review this one please. Adds webpack 4 support whilst keeping 1/2/3 support too. Tests are passing.

**Comment by blaadje** [comment]
Merge it soooon 😀

**Comment by klimashkin** [comment]
This is the last loader that prevents us upgrading to webpack 4. @kisenka Can we help with something here?

**Comment by kisenka** [comment]
Done, svg-sprite-loader@3.7.0. 
Huge thanks @rynclark for supporting webpack 4! Actually I on vacation now, but I understand guys how this feature is important for you.
Can I close #241 and #249?

**Comment by rynclark** [comment]
Yeah I think you can close #248 too

**Pull request merged**
